cuda_graph_config:
  enable_padding: true
  max_batch_size: 4
print_iter_log: true
kv_cache_config:
  dtype: fp8
  free_gpu_memory_fraction: 0.75
stream_interval: 10
moe_config:
  backend: CUTLASS
speculative_config:
  decoding_type: MTP
  num_nextn_predict_layers: 3
tensor_parallel_size: 8
moe_expert_parallel_size: 8
trust_remote_code: true
max_num_tokens: 5248
max_seq_len: 2068
