cuda_graph_config:
  enable_padding: true
  max_batch_size: 1024
dtype: bfloat16
enable_chunked_prefill: true
kv_cache_config:
  dtype: fp8
  free_gpu_memory_fraction: 0.8
max_num_tokens: 4096
moe_config:
  backend: CUTLASS
tensor_parallel_size: 4
trust_remote_code: true
