repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.1.13
    hooks:
    -   id: remove-crlf
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
        exclude: |
            (?x)^(.*cubin.cpp)$
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.6.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables']
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.0
    hooks:
    -   id: clang-format
        types_or: [c++, c, cuda]
        exclude: |
            (?x)^(.*cubin.cpp$ | .*fmha_cubin.h)$
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    -   id: cmake-format
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    -   id: codespell
        args:
        - --skip=".git,3rdparty"
        - --exclude-file=examples/whisper/tokenizer.py
        - --ignore-words-list=rouge,inout,atleast,strat,nd
        exclude: 'tests/llm-test-defs/turtle/test_input_files'
