[project]
name = "unknown-package"
version = "0.1.0"
description = ""
authors = [
    {name = "TensorRT LLM [90828364+tensorrt-cicd@users.noreply.github.com]"}
]
requires-python = ">=3.10,<3.13"
dependencies = [
    "ftfy (>=6.3.1,<7.0.0)",
    "av (==12.3.0)",
    "rotary-embedding-torch (==0.5.3)",
    "fabric (>=3.2.2,<4.0.0)",
    "contexttimer (>=0.3.3,<0.4.0)",
    "ray (>=2.53.0,<3.0.0)",
    "protobuf (>=6.33.5,<7.0.0)",
    "bitsandbytes (>=0.39.0)",
    "rpyc (==6.0.0)",
    "galore-torch (>=1.0,<2.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
