[tool.poetry]
name = "unknown-package"
version = "0.1.0"
description = ""
authors = ["TensorRT LLM [90828364+tensorrt-cicd@users.noreply.github.com]"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
ftfy = "^6.3.1"
av = "12.3.0"
rotary-embedding-torch = "0.5.3"
fabric = "^3.2.2"
contexttimer = "^0.3.3"
ray = "^2.50.1"
protobuf = "^6.33.0"
bitsandbytes = ">=0.39.0"
rpyc = "6.0.0"
galore-torch = "^1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
