[project]
name = "unknown-package"
version = "0.1.0"
description = ""
authors = [
    {name = "TensorRT LLM [90828364+tensorrt-cicd@users.noreply.github.com]"}
]
requires-python = ">=3.10,<3.13"
dependencies = [
    "pytest (==7.2.2)",
    "pytest-cpp (==2.3.0)",
    "pytest-xdist (==3.2.1)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
