[project]
name = "wordllama-serve"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.23.0",
    "wordllama>=0.4.0.post1",
]
