[tool.poetry]
name = "unknown-package"
version = "0.1.0"
description = ""
authors = ["TensorRT LLM [90828364+tensorrt-cicd@users.noreply.github.com]"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
decord = "^0.6.0"
timm = "^1.0.21"
av = "^16.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
