hostname: localhost
port: 42661
backend: pytorch
disagg_cluster:
  cluster_uri: etcd://localhost:2379
  cluster_name: test_cluster
  heartbeat_interval_sec: 1
  inactive_timeout_sec: 2
context_servers:
  router:
    type: round_robin
generation_servers:
  router:
    type: round_robin
