cuda_graph_config:
  enable_padding: true
  max_batch_size: 64
enable_attention_dp: false
kv_cache_config:
  dtype: fp8
  free_gpu_memory_fraction: 0.9
moe_config:
  backend: TRTLLM
print_iter_log: true
tensor_parallel_size: 8
moe_expert_parallel_size: 8
trust_remote_code: true
backend: pytorch
max_num_tokens: 2048
max_seq_len: 9284
