env_overrides:
  TRTLLM_ENABLE_PDL: 1
  NCCL_GRAPH_REGISTER: 0
max_batch_size: 384
print_iter_log: true
tensor_parallel_size: 4
moe_expert_parallel_size: 4
trust_remote_code: true
max_num_tokens: 20000
max_seq_len: 9236
