cuda_graph_config:
  enable_padding: true
  max_batch_size: 512
enable_attention_dp: true
print_iter_log: true
kv_cache_config:
  dtype: fp8
  free_gpu_memory_fraction: 0.8
stream_interval: 10
moe_config:
  backend: CUTLASS
attention_dp_config:
  batching_wait_iters: 0
  enable_balance: true
  timeout_iters: 60
tensor_parallel_size: 8
moe_expert_parallel_size: 8
trust_remote_code: true
backend: pytorch
max_num_tokens: 1344
max_seq_len: 2068
