[tool.poetry]
name = "unknown-package"
version = "0.1.0"
description = ""
authors = ["TensorRT LLM [90828364+tensorrt-cicd@users.noreply.github.com]"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
datasets = "3.1.0"
evaluate = "^0.4.6"
rouge-score = "^0.1.2"
transformers = ">=4.56.0"
transformers-stream-generator = "^0.0.5"
sentencepiece = ">=0.1.99"
tiktoken = "^0.12.0"
einops = "^0.8.1"
gradio = "4.44.1"
mdtex2html = "^1.3.1"
sse-starlette = "^3.0.2"
aiohttp-sse-client = "^0.2.1"
openai = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
